In [18]:
import numpy as np
import pandas as pd
import sklearn as sk

In [19]:
df = pd.read_csv(r"C:\Users\jemin\Downloads\Datamites\trainRF.csv")

df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [20]:
#1 Create X containing only ram, battery_power, and int_memory. 

x = df[['ram','battery_power','int_memory']]

x

       ram  battery_power  int_memory
0     2549            842           7
1     2631           1021          53
2     2603            563          41
3     2769            615          10
4     1411           1821          44
...    ...            ...         ...
1995   668            794           2
1996  2032           1965          39
1997  3057           1911          36
1998   869           1512          46
1999  3919            510          45

[2000 rows x 3 columns]

In [21]:
#2 Create y containing the price_range column. 

y = df['price_range']

y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [22]:
#3 Print the shapes of X and y. Explain what each output means. 

print(x.shape)
print(y.shape)

# (rows, columns)

(2000, 3)
(2000,)

In [23]:
#4 Create X using ram, battery_power, int_memory, n_cores, and px_height. 

x = df[['ram','battery_power','int_memory','n_cores','px_height']]

x

       ram  battery_power  int_memory  n_cores  px_height
0     2549            842           7        2         20
1     2631           1021          53        3        905
2     2603            563          41        5       1263
3     2769            615          10        6       1216
4     1411           1821          44        2       1208
...    ...            ...         ...      ...        ...
1995   668            794           2        6       1222
1996  2032           1965          39        4        915
1997  3057           1911          36        8        868
1998   869           1512          46        5        336
1999  3919            510          45        6        483

[2000 rows x 5 columns]

In [24]:
#5 Create X using every column except price_range. Create y using only price_range. 

x = df.drop(columns = ['price_range'])
y = df['price_range']

print(x)
print(y)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]
0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [34]:
#6 Count how many phones belong to each price_range category. Which category has the most phones?  

print(y.value_counts())

print(y.value_counts().idxmax())

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64
1

In [37]:
#7 Write code to count missing values in every column. Identify whether ram has any missing values. 

print(df.isnull().sum())

print(df['ram'].isnull().sum())

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64
0

In [42]:
#8 Count how many duplicate rows exist in the dataset. Do not remove them yet. 

print(df.duplicated().sum())

0

In [46]:
#9 Display the minimum, maximum, mean, and median of ram. Use Python code rather than calculating manually. 

print(f"Minimum of ram : {df['ram'].min()}")
print(f"Maximum of ram : {df['ram'].max()}")
print(f"Mean of ram : {df['ram'].mean()}")
print(f"Median of ram : {df['ram'].median()}")

Minimum of ram : 256
Maximum of ram : 3998
Mean of ram : 2124.213
Median of ram : 2146.5

In [54]:
#10 
"""
Create X with ram, battery_power, int_memory, and px_height. Create y with price_range. 

Then check: 
 The shapes of X and y 
 Whether X contains missing values 
 The number of unique categories in y
"""

x = df[['ram','battery_power','int_memory','px_height']]
y = df['price_range']

print(f"\nShape of x : {x.shape}")
print(f"\nShape of y : {y.shape}")

miss = x.isnull().sum() == 0
print(miss)

unique = y.nunique()
print(unique)

Shape of x : (2000, 4)

Shape of y : (2000,)
ram              True
battery_power    True
int_memory       True
px_height        True
dtype: bool
4