In [2]:
import numpy as np
import pandas as pd
import sklearn as sk

# ML4

In [3]:
df = pd.read_csv(r"C:\Users\jemin\Downloads\Datamites\trainRF.csv")

df

      battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0               842     0          2.2  ...             0     1            1
1              1021     1          0.5  ...             1     0            2
2               563     1          0.5  ...             1     0            2
3               615     1          2.5  ...             0     0            2
4              1821     1          1.2  ...             1     0            1
...             ...   ...          ...  ...           ...   ...          ...
1995            794     1          0.5  ...             1     0            0
1996           1965     1          2.6  ...             1     1            2
1997           1911     0          0.9  ...             1     0            3
1998           1512     0          0.9  ...             1     1            0
1999            510     1          2.0  ...             1     1            3

[2000 rows x 21 columns]

In [4]:
#1 Create `X` using `ram`, `battery_power`, and `int_memory`. Create `y` using `price_range`. Display the first five rows of both. 

x = df[['ram','battery_power','int_memory']]
y = df['price_range']

print(x.head())
print(y.head())

    ram  battery_power  int_memory
0  2549            842           7
1  2631           1021          53
2  2603            563          41
3  2769            615          10
4  1411           1821          44
0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [5]:
#2 Check the number of missing values in every column of `X`. 

miss = x.isnull().sum()

miss

ram              0
battery_power    0
int_memory       0
dtype: int64

In [6]:
#3 Create a new DataFrame named `df_clean` by filling missing values in `ram` with the median RAM. Do not modify the original `df`. 

df_clean = df.copy()

df_clean['ram'] = df_clean['ram'].fillna(df_clean['ram'].median())

df_clean

      battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0               842     0          2.2  ...             0     1            1
1              1021     1          0.5  ...             1     0            2
2               563     1          0.5  ...             1     0            2
3               615     1          2.5  ...             0     0            2
4              1821     1          1.2  ...             1     0            1
...             ...   ...          ...  ...           ...   ...          ...
1995            794     1          0.5  ...             1     0            0
1996           1965     1          2.6  ...             1     1            2
1997           1911     0          0.9  ...             1     0            3
1998           1512     0          0.9  ...             1     1            0
1999            510     1          2.0  ...             1     1            3

[2000 rows x 21 columns]

In [7]:
#4 Create a new DataFrame named `df_unique` by removing duplicate rows. Display the number of rows before and after removal.

print(f"Rows before removal: {df.shape[0]}")

df_unique = df.drop_duplicates()

print(f"Rows after removal: {df_unique.shape[0]}")

Rows before removal: 2000
Rows after removal: 2000

In [8]:
#5 Create `X` using `ram` and `battery_power`, and create `y` using `price_range`. Display the shape of `X`. 

x = df[['ram','battery_power']]
y = df['price_range']

x.shape

(2000, 2)

In [9]:
#6 Split `X` and `y` into training and testing sets using `train_test_split`. Use `test_size=0.2` and `random_state=42`.

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2,
    random_state = 42
)

In [10]:
#7 Print the shapes of `X_train`, `X_test`, `y_train`, and `y_test` from Question 6. 

print(f"shape of X_train : {X_train.shape}")
print(f"shape of X_test : {X_test.shape}")
print(f"shape of y_test : {y_test.shape}")
print(f"shape of y_train : {y_train.shape}")

shape of X_train : (1600, 2)
shape of X_test : (400, 2)
shape of y_test : (400,)
shape of y_train : (1600,)

In [11]:
#8 Use `StandardScaler` to scale `X_train` and `X_test`. Fit the scaler on training data only, then transform both datasets. 

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [12]:
#9 Display the first five rows of the scaled training features. Use the variable names from Question 8.

X_train_scaled[:5]

array([[-0.58047631,  1.54835969],
       [ 1.33645326, -1.3795348 ],
       [-0.65730159, -0.01091435],
       [ 1.28832176, -1.04362132],
       [-0.48976694,  0.48841649]])

In [13]:
#10 Use `LogisticRegression` to train a classification model on the training data from Question 8. Predict `price_range` for `X_test` and display the first 10 predictions.

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(y_pred[:10])

[0 2 1 3 1 1 2 0 2 1]

# ML5

In [14]:
#1 Use `accuracy_score` to compare `y_test` and `y_pred`. Print the accuracy. 

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.8175

In [15]:
#2 Convert the accuracy score into a percentage and print it with the `%` symbol. 

convert = accuracy * 100

print(f"{convert}%")

81.75%

In [16]:
#3 Use `confusion_matrix` to compare actual labels `y_test` with predictions `y_pred`. Display the matrix.

from sklearn.metrics import confusion_matrix

compare = confusion_matrix(y_test, y_pred)

print(compare)

[[98  7  0  0]
 [ 8 70 13  0]
 [ 0 10 71 11]
 [ 0  0 24 88]]

In [17]:
#4 Use `classification_report` to display precision, recall, F1-score and support for each price category. 

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       105
           1       0.80      0.77      0.79        91
           2       0.66      0.77      0.71        92
           3       0.89      0.79      0.83       112

    accuracy                           0.82       400
   macro avg       0.82      0.82      0.81       400
weighted avg       0.83      0.82      0.82       400

In [19]:
#5 Create a comparison between `y_test` and `y_pred`. Count how many predictions are correct and how many are incorrect. 

correct = (y_test == y_pred).sum()
incorrect = (y_test != y_pred).sum()

print("Correct Predictions:", correct)
print("Incorrect Predictions:", incorrect)

Correct Predictions: 327
Incorrect Predictions: 73

In [21]:
#6 Find the test rows where `y_pred` does not match `y_test`. Display the first 5 incorrect predictions alongside their actual labels.

incorrect = y_test != y_pred

result = X_test[incorrect].copy()

result["Actual"] = y_test[incorrect]
result["Predicted"] = y_pred[incorrect]

print(result.head(5))

       ram  battery_power  Actual  Predicted
65    3366            616       3          2
1292  1300           1365       0          1
374   2542           1334       3          2
1664  1882           1288       2          1
1927  3155           1023       3          2

In [23]:
#7 Calculate the accuracy separately for each actual `price_range` category (0, 1, 2 and 3).

from sklearn.metrics import accuracy_score

for category in [0, 1, 2, 3]:
    mask = y_test == category

    accuracy = accuracy_score(y_test[mask], y_pred[mask])

    print(f"Price Range {category} Accuracy: {accuracy:.2%}")

Price Range 0 Accuracy: 93.33%
Price Range 1 Accuracy: 76.92%
Price Range 2 Accuracy: 77.17%
Price Range 3 Accuracy: 78.57%

In [25]:
#8 Train a `KNeighborsClassifier` using `X_train_scaled` and `y_train`. Predict labels for `X_test_scaled` and store them in `y_pred_knn`.

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print(y_pred_knn[:10])

[0 2 1 3 1 1 2 0 2 1]

In [29]:
#9 Calculate and print the accuracy of Logistic Regression (`y_pred`) and KNN (`y_pred_knn`). Identify which has the higher test accuracy. 

from sklearn.metrics import accuracy_score

log_accuracy = accuracy_score(y_test, y_pred) * 100
knn_accuracy = accuracy_score(y_test, y_pred_knn) * 100

print(f"Accuracy of Logistic Regression : {log_accuracy}%")
print(f"Accuracy of KNN : {knn_accuracy}%")

if log_accuracy > knn_accuracy:
    print("Logistic Regression has higher test accuracy.")
elif knn_accuracy > log_accuracy:
    print("KNN has higher test accuracy.")
else:
    print("Both models have equal test accuracy.")

Accuracy of Logistic Regression : 81.75%
Accuracy of KNN : 76.75%
Logistic Regression has higher test accuracy.

In [ ]:
#10 Suppose a phone retailer uses your model to assign price categories. Based on your evaluation results, explain one risk of using the model and one way to improve it.

"""
-> Accuracy = 81.75%: The model correctly predicts about 82 out of every 100 phones on this test dataset.

-> Improvement: We can train and evaluate different models, such as KNN, Logistic Regression, and Random Forest, and compare their results.
"""

# ML6

In [ ]:
#1