In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

# ML4

In [2]:
df = pd.read_csv(r"C:\Users\jemin\Downloads\Datamites\trainRF.csv")

df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [3]:
#1 Create `X` using `ram`, `battery_power`, and `int_memory`. Create `y` using `price_range`. Display the first five rows of both. 

x = df[['ram','battery_power','int_memory']]
y = df['price_range']

print(x.head())
print(y.head())

    ram  battery_power  int_memory
0  2549            842           7
1  2631           1021          53
2  2603            563          41
3  2769            615          10
4  1411           1821          44
0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [4]:
#2 Check the number of missing values in every column of `X`. 

miss = x.isnull().sum()

miss

ram              0
battery_power    0
int_memory       0
dtype: int64

In [5]:
#3 Create a new DataFrame named `df_clean` by filling missing values in `ram` with the median RAM. Do not modify the original `df`. 

df_clean = df.copy()

df_clean['ram'] = df_clean['ram'].fillna(df_clean['ram'].median())

df_clean

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [6]:
#4 Create a new DataFrame named `df_unique` by removing duplicate rows. Display the number of rows before and after removal.

print(f"Rows before removal: {df.shape[0]}")

df_unique = df.drop_duplicates()

print(f"Rows after removal: {df_unique.shape[0]}")

Rows before removal: 2000
Rows after removal: 2000

In [7]:
#5 Create `X` using `ram` and `battery_power`, and create `y` using `price_range`. Display the shape of `X`. 

x = df[['ram','battery_power']]
y = df['price_range']

x.shape

(2000, 2)

In [8]:
#6 Split `X` and `y` into training and testing sets using `train_test_split`. Use `test_size=0.2` and `random_state=42`.

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2,
    random_state = 42
)

In [9]:
#7 Print the shapes of `X_train`, `X_test`, `y_train`, and `y_test` from Question 6. 

print(f"shape of X_train : {X_train.shape}")
print(f"shape of X_test : {X_test.shape}")
print(f"shape of y_test : {y_test.shape}")
print(f"shape of y_train : {y_train.shape}")

shape of X_train : (1600, 2)
shape of X_test : (400, 2)
shape of y_test : (400,)
shape of y_train : (1600,)

In [10]:
#8 Use `StandardScaler` to scale `X_train` and `X_test`. Fit the scaler on training data only, then transform both datasets. 

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [11]:
#9 Display the first five rows of the scaled training features. Use the variable names from Question 8.

X_train_scaled[:5]

array([[-0.58047631,  1.54835969],
       [ 1.33645326, -1.3795348 ],
       [-0.65730159, -0.01091435],
       [ 1.28832176, -1.04362132],
       [-0.48976694,  0.48841649]])

In [12]:
#10 Use `LogisticRegression` to train a classification model on the training data from Question 8. Predict `price_range` for `X_test` and display the first 10 predictions.

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(y_pred[:10])

[0 2 1 3 1 1 2 0 2 1]

# ML5

In [13]:
#1 Use `accuracy_score` to compare `y_test` and `y_pred`. Print the accuracy. 

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.8175

In [14]:
#2 Convert the accuracy score into a percentage and print it with the `%` symbol. 

convert = accuracy * 100

print(f"{convert}%")

81.75%

In [15]:
#3 Use `confusion_matrix` to compare actual labels `y_test` with predictions `y_pred`. Display the matrix.

from sklearn.metrics import confusion_matrix

compare = confusion_matrix(y_test, y_pred)

print(compare)

[[98  7  0  0]
 [ 8 70 13  0]
 [ 0 10 71 11]
 [ 0  0 24 88]]

In [16]:
#4 Use `classification_report` to display precision, recall, F1-score and support for each price category. 

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       105
           1       0.80      0.77      0.79        91
           2       0.66      0.77      0.71        92
           3       0.89      0.79      0.83       112

    accuracy                           0.82       400
   macro avg       0.82      0.82      0.81       400
weighted avg       0.83      0.82      0.82       400

In [17]:
#5 Create a comparison between `y_test` and `y_pred`. Count how many predictions are correct and how many are incorrect. 

correct = (y_test == y_pred).sum()
incorrect = (y_test != y_pred).sum()

print("Correct Predictions:", correct)
print("Incorrect Predictions:", incorrect)

Correct Predictions: 327
Incorrect Predictions: 73

In [18]:
#6 Find the test rows where `y_pred` does not match `y_test`. Display the first 5 incorrect predictions alongside their actual labels.

incorrect = y_test != y_pred

result = X_test[incorrect].copy()

result["Actual"] = y_test[incorrect]
result["Predicted"] = y_pred[incorrect]

print(result.head(5))

       ram  battery_power  Actual  Predicted
65    3366            616       3          2
1292  1300           1365       0          1
374   2542           1334       3          2
1664  1882           1288       2          1
1927  3155           1023       3          2

In [19]:
#7 Calculate the accuracy separately for each actual `price_range` category (0, 1, 2 and 3).

from sklearn.metrics import accuracy_score

for category in [0, 1, 2, 3]:
    mask = y_test == category

    accuracy = accuracy_score(y_test[mask], y_pred[mask])

    print(f"Price Range {category} Accuracy: {accuracy:.2%}")

Price Range 0 Accuracy: 93.33%
Price Range 1 Accuracy: 76.92%
Price Range 2 Accuracy: 77.17%
Price Range 3 Accuracy: 78.57%

In [20]:
#8 Train a `KNeighborsClassifier` using `X_train_scaled` and `y_train`. Predict labels for `X_test_scaled` and store them in `y_pred_knn`.

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

print(y_pred_knn[:10])

[0 2 1 3 1 1 2 0 2 1]

In [21]:
#9 Calculate and print the accuracy of Logistic Regression (`y_pred`) and KNN (`y_pred_knn`). Identify which has the higher test accuracy. 

from sklearn.metrics import accuracy_score

log_accuracy = accuracy_score(y_test, y_pred) * 100
knn_accuracy = accuracy_score(y_test, y_pred_knn) * 100

print(f"Accuracy of Logistic Regression : {log_accuracy}%")
print(f"Accuracy of KNN : {knn_accuracy}%")

if log_accuracy > knn_accuracy:
    print("Logistic Regression has higher test accuracy.")
elif knn_accuracy > log_accuracy:
    print("KNN has higher test accuracy.")
else:
    print("Both models have equal test accuracy.")

Accuracy of Logistic Regression : 81.75%
Accuracy of KNN : 76.75%
Logistic Regression has higher test accuracy.

In [22]:
#10 Suppose a phone retailer uses your model to assign price categories. Based on your evaluation results, explain one risk of using the model and one way to improve it.

"""
-> Accuracy = 81.75%: The model correctly predicts about 82 out of every 100 phones on this test dataset.

-> Improvement: We can train and evaluate different models, such as KNN, Logistic Regression, and Random Forest, and compare their results.
"""

'\n-> Accuracy = 81.75%: The model correctly predicts about 82 out of every 100 phones on this test dataset.\n\n-> Improvement: We can train and evaluate different models, such as KNN, Logistic Regression, and Random Forest, and compare their results.\n'

# ML6

In [23]:
#1 Import RandomForestClassifier, create a model with random_state=42, and train it using the training dataset. Use the original, unscaled X_train and y_train.

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(random_state=42)

model_rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [24]:
#2 Predict the price categories for X_test and calculate the model's test accuracy as a percentage. 

from sklearn.metrics import accuracy_score

y_pred_rf = model_rf.predict(X_test)

print(y_pred_rf)


rf_accuracy = accuracy_score(y_test, y_pred_rf)

print(f"Accuracy : {rf_accuracy * 100:.2f}%")

[0 2 1 3 1 1 2 0 2 1 0 1 1 3 2 2 3 3 1 0 0 1 1 1 0 0 3 2 2 0 1 0 3 0 1 1 3
 0 3 0 2 3 2 0 3 2 1 1 3 1 3 1 0 0 1 1 1 2 0 0 0 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 1 3 2 2 3 2 1 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 1 0 3 2 0 1 1 0
 0 2 1 2 2 2 3 0 2 1 3 2 2 3 2 0 3 0 1 3 0 2 2 0 2 1 0 0 2 3 1 2 3 0 0 0 2
 2 2 3 1 1 0 3 2 0 1 0 2 2 3 2 2 1 0 0 2 2 3 3 1 1 0 3 1 2 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 2 2 0 1 2 1 1 2 2 2 3 3 0 2 0 0 0 2 1 1 3 1 0 3 1 0 3 2
 3 0 0 2 1 2 0 0 2 0 2 3 2 0 0 3 3 0 2 3 3 3 0 3 1 2 3 3 2 0 1 3 3 0 3 3 3
 2 3 0 1 2 2 2 2 0 2 2 2 2 2 0 0 1 0 2 3 1 3 1 0 3 1 2 0 0 3 0 2 2 3 3 3 0
 0 0 1 3 3 0 1 1 2 0 2 3 3 3 2 3 2 0 2 1 2 1 0 0 0 3 2 3 1 0 2 0 1 3 3 1 2
 3 2 1 2 0 0 3 1 3 2 0 2 2 1 1 2 3 1 0 0 3 3 0 3 0 0 2 0 1 2 2 3 3 1 3 2 2
 3 3 3 2 1 2 0 3 1 3 3 0 2 3 1 3 3 3 0 0 2 3 0 0 3 3 1 1 1 2]
Accuracy : 79.00%

In [25]:
#3 Compare the test accuracy of Logistic Regression, KNN, and Random Forest. Identify which model has the highest accuracy.

if rf_accuracy > knn_accuracy and rf_accuracy > log_accuracy:
    print(f"Rainforest model has highest accuracy with {rf_accuracy * 100:.2f}%")

elif knn_accuracy > rf_accuracy and knn_accuracy > log_accuracy:
    print(f"Knn model has highest accuracy with {rf_accuracy * 100:.2f}%")

elif log_accuracy > rf_accuracy and log_accuracy > knn_accuracy:
    print(f"Logistic regretion model has highest accuracy with {rf_accuracy * 100:.2f}%")

else:    
    print("Two or more models have equal accuracy.")

Logistic regretion model has highest accuracy with 79.00%

In [26]:
#4 Train Random Forest models using n_esmators=50, 100, and 200. Compare their test accuracies and identify the best result.

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_rf50 = RandomForestClassifier(n_estimators=50, random_state=42)
model_rf100 = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf200 = RandomForestClassifier(n_estimators=200, random_state=42)

model_rf50.fit(X_train, y_train)
model_rf100.fit(X_train, y_train)
model_rf200.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [27]:
#5 Train three Random Forest models with max_depth=5, 10, and 20. Keep the other parameters the same and compare their test accuracies.

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_rf5 = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
model_rf10 = RandomForestClassifier(n_estimators=50, max_depth=10, random_state=42)
model_rf20 = RandomForestClassifier(n_estimators=50, max_depth=20, random_state=42)

model_rf5.fit(X_train,y_train)
model_rf10.fit(X_train,y_train)
model_rf20.fit(X_train,y_train)

pred_rf5 = model_rf5.predict(X_test)
pred_rf10 = model_rf10.predict(X_test)
pred_rf20 = model_rf20.predict(X_test)

accu_rf5 = accuracy_score(y_test, pred_rf5)
accu_rf10 = accuracy_score(y_test, pred_rf10)
accu_rf20 = accuracy_score(y_test, pred_rf20)

print(f"Accuracy of with max depth = 5 is {accu_rf5 * 100:.2f}%")
print(f"Accuracy of with max depth = 10 is {accu_rf10 * 100:.2f}%")
print(f"Accuracy of with max depth = 20 is {accu_rf20 * 100:.2f}%")

Accuracy of with max depth = 5 is 82.50%
Accuracy of with max depth = 10 is 80.00%
Accuracy of with max depth = 20 is 78.50%

In [28]:
#6 Compare Random Forest models with min_samples_split=2, 5, and 10. Find which setting gives the highest test accuracy.

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_rf_2 = RandomForestClassifier(n_estimators=50, min_samples_split=2, random_state=42, max_depth=5)
model_rf_5 = RandomForestClassifier(n_estimators=50, min_samples_split=5, random_state=42, max_depth=5)
model_rf_10 = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=42, max_depth=5)

model_rf_2.fit(X_train, y_train)
model_rf_5.fit(X_train, y_train)
model_rf_10.fit(X_train, y_train)

pred_rf_2 = model_rf_2.predict(X_test)
pred_rf_5 = model_rf_5.predict(X_test)
pred_rf_10 = model_rf_10.predict(X_test)

accu_rf_2 = accuracy_score(y_test, pred_rf_2)
accu_rf_5 = accuracy_score(y_test, pred_rf_5)
accu_rf_10 = accuracy_score(y_test, pred_rf_10)

accuracies = {
    2: accu_rf_2,
    5: accu_rf_5,
    10: accu_rf_10
}

best_split = max(accuracies, key=accuracies.get)

print(f"Best min_samples_split = {best_split}")
print(f"Test accuracy = {accuracies[best_split] * 100:.2f}%")

Best min_samples_split = 2
Test accuracy = 82.50%

In [29]:
#7 Use 5-fold cross-validation to evaluate a Random Forest model on the training dataset. Calculate the mean cross-validation accuracy.

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model_rf = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)

cv_scores = cross_val_score(model_rf, X_train, y_train, cv=5, scoring='accuracy')

print("Fold accuracies:", cv_scores)
print(f"Mean CV Accuracy: {cv_scores.mean() * 100:.2f}%")

Fold accuracies: [0.796875 0.8125   0.815625 0.80625  0.834375]
Mean CV Accuracy: 81.31%

In [30]:
#8 
"""
Use GridSearchCV 
Find the best Random Forest parameters by testing: 
 n_esmators: 50, 100 
 max_depth: 5, 10, None 
 
Use 5-fold cross-validation and display the best parameters and best cross-validation score.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

model_rfc = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10, None]
}

grid_search = GridSearchCV(
    estimator=model_rfc,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print(f"Best CV Accuracy: {grid_search.best_score_ * 100:.2f}%")

Best Parameters: {'max_depth': 5, 'n_estimators': 50}
Best CV Accuracy: 81.31%

In [31]:
#9 Use the best estimator from GridSearchCV to predict X_test. Calculate its test accuracy and compare it with your original Random Forest model.

from sklearn.metrics import accuracy_score

best_model = grid_search.best_estimator_

pred_best = best_model.predict(X_test)

best_accuracy = accuracy_score(y_test, pred_best)

print(f"Original RF Accuracy: {rf_accuracy * 100:.2f}%")
print(f"Best RF Test Accuracy: {best_accuracy * 100:.2f}%")

if best_accuracy > rf_accuracy:
    print("GridSearchCV model performed better.")
elif best_accuracy < rf_accuracy:
    print("Original Random Forest model performed better.")
else:
    print("Both models have the same test accuracy.")

Original RF Accuracy: 79.00%
Best RF Test Accuracy: 82.50%
GridSearchCV model performed better.

In [32]:
#10 
"""
A phone retailer wants to use your model to assign price categories. 
Compare your original and tuned models using test accuracy and cross-validation results. 
Recommend one model and explain how you would reduce the risk of incorrect price classifications.
"""

from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

# 1. Original model test accuracy
original_pred = model_rfs.predict(X_test)
original_test_accuracy = accuracy_score(y_test, original_pred)

# 2. Tuned model test accuracy
tuned_model = grid_search.best_estimator_
tuned_pred = tuned_model.predict(X_test)
tuned_test_accuracy = accuracy_score(y_test, tuned_pred)

# 3. Cross-validation scores for both models
original_cv_scores = cross_val_score(
    model_rfs, X_train, y_train, cv=5, scoring='accuracy'
)

tuned_cv_scores = cross_val_score(
    tuned_model, X_train, y_train, cv=5, scoring='accuracy'
)

# 4. Display comparison
print("Original Random Forest")
print(f"Test Accuracy: {original_test_accuracy * 100:.2f}%")
print(f"Mean CV Accuracy: {original_cv_scores.mean() * 100:.2f}%")

print("\nTuned Random Forest")
print(f"Test Accuracy: {tuned_test_accuracy * 100:.2f}%")
print(f"Mean CV Accuracy: {tuned_cv_scores.mean() * 100:.2f}%")

# 5. Recommend a model based on test accuracy
if tuned_test_accuracy > original_test_accuracy:
    print("\nRecommendation: Choose the tuned model.")
elif tuned_test_accuracy < original_test_accuracy:
    print("\nRecommendation: Choose the original model.")
else:
    print("\nBoth models have equal test accuracy. Compare CV consistency.")

NameError: name 'model_rfs' is not defined

# ML7

In [ ]:
#1 
"""
A mobile retailer wants to classify phones into price categories. 

1. Train a RandomForestClassifier with n_estimators=100 and random_state=42. 
2. Predict on X_test. 
3. Calculate and print test accuracy as a percentage.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

model_rfs.fit(X_train, y_train)

pred_rfs = model_rfs.predict(X_test)

accu_rfs = accuracy_score(y_test, pred_rfs)

print(f"Accuracy of RFS model is {accu_rfs * 100:.2f}%")

In [ ]:
#2 
"""
A single train/test split may give an unreliable estimate of model performance. 

1. Create a RandomForestClassifier with n_estimators=100 and random_state=42. 
2. Use cross_val_score() with cv=5 on X and y. 
3. Print all five accuracy scores.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv_score = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

print(cv_score)

In [ ]:
#3 
"""
A retailer wants one summary score from the five folds. 

1. Perform 5-fold cross-validation on a RandomForestClassifier. 
2. Calculate the mean of the five scores. 
3. Print the mean accuracy as a percentage. 
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv_score = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

print(f"{cv_score.mean() * 100:.2f}%")

In [ ]:
#4
"""
Two models have similar mean accuracy, but one performs inconsistently across folds. 

1. Obtain five cross-validation accuracy scores for a Random Forest. 
2. Calculate their standard deviation using NumPy. 
3. Explain what a higher standard deviation suggests about model performance.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv_score = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

print(cv_score)
print("Standard deviation:", np.std(cv_score))

In [ ]:
#5
"""
Your team wants to know whether the cross-validation result is similar to the held-out test result. 

1. Train a Random Forest on X_train and y_train. 
2. Calculate its test accuracy using X_test and y_test. 
3. Calculate its 5-fold cross-validation mean using only the training data. 
4. Compare the two scores. 
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

model_rfs.fit(X_train, y_train)
pred_rfs = model_rfs.predict(X_test)
accu_rfs = accuracy_score(y_test, pred_rfs)

cv = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

if cv.mean() > accu_rfs:
    print(f"Cv score is higher than normal accuracy with {cv.mean() * 100:.2f}%")
elif accu_rfs > cv.mean():
    print(f"Normal accuracy score is higher than cv score accuray with {accu_rfs * 100:.2f}%")
else:
    print(f"Both accuracy is similar which is {accu_rfs * 100:.2f}%")

In [ ]:
#6 
"""
A data scientist wants to select a model for predicting phone price categories. Use 5-fold cross-validation to compare: 

 LogisticRegression(max_iter=1000) — use scaled features. 
 KNeighborsClassifier(n_neighbors=5) — use scaled features. 
 RandomForestClassifier(n_esmators=100, random_state=42) — use unscaled features. 

Print the mean accuracy for each model. Use a Pipeline for the scaled models to avoid data leakage between folds. 
"""

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Logistic Regression with scaling
model_log = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))

cv_log = cross_val_score(model_log, X_train, y_train, cv=5, scoring='accuracy')

# KNN with scaling
model_knn = make_pipeline(StandardScaler(),KNeighborsClassifier(n_neighbors=5))

cv_knn = cross_val_score(model_knn, X_train, y_train, cv=5, scoring='accuracy')

# Random Forest without scaling
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

cv_rf = cross_val_score(model_rf, X_train, y_train, cv=5, scoring='accuracy')

# Print mean accuracies
print(f"Logistic Regression: {cv_log.mean() * 100:.2f}%")
print(f"KNN:                {cv_knn.mean() * 100:.2f}%")
print(f"Random Forest:      {cv_rf.mean() * 100:.2f}%")

In [ ]:
#7
"""
Your team wants to compare 3-fold and 5-fold cross-validation. 

1. Evaluate the same Random Forest using cv=3. 
2. Evaluate it again using cv=5. 
3. Compare the mean accuracy scores. 
4. Explain one difference between the two approaches. 
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv_3 = cross_val_score(model_rfs, X_train, y_train, cv=3, scoring='accuracy')
cv_5 = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

print(f"Cv score with fold 3 is {cv_3.mean() * 100:.2f}%")
print(f"Cv score with fold 5 is {cv_5.mean() * 100:.2f}%")

#Cv_score is become better with fold 3

In [ ]:
#8 
"""
Accuracy alone may not show which price categories the model struggles to classify. 

1. Use cross_validate() with a Random Forest. 
2. Evaluate accuracy, precision_macro, recall_macro, and f1_macro. 
3. Print the mean score for each metric.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv_rfs = cross_validate(model_rfs,X_train,y_train,cv=5,
                        scoring=["accuracy", "precision_macro", "recall_macro", "f1_macro"])

print(f"Mean Accuracy:  {cv_rfs['test_accuracy'].mean() * 100:.2f}%")
print(f"Mean Precision: {cv_rfs['test_precision_macro'].mean() * 100:.2f}%")
print(f"Mean Recall:    {cv_rfs['test_recall_macro'].mean() * 100:.2f}%")
print(f"Mean F1-score:  {cv_rfs['test_f1_macro'].mean() * 100:.2f}%")

In [ ]:
#9 
"""
A retailer wants a model that performs consistently, not just one with high average accuracy. 

1. Run 5-fold cross-validation on a Random Forest. 
2. Display each fold's accuracy. 
3. Identify the highest and lowest fold scores. 
4. Calculate the difference between them and explain what it tells you. 
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model_rfs = RandomForestClassifier(n_estimators=100, random_state=42)

cv = cross_val_score(model_rfs, X_train, y_train, cv=5, scoring='accuracy')

print("Each fold's accuracy:", cv)

print(f"Highest fold score is {cv.min() * 100:.2f}%")
print(f"Lowest fold score is {cv.max() * 100:.2f}%")
print(f"Difference between them is {abs(cv.max() - cv.min()) * 100:.2f}%")

In [ ]:
#10 
"""
A phone retailer will use your model to assign price categories to new phones. You have evaluated Logistic Regression, KNN, and Random Forest using cross-validation and a separate test set. 

Write code and a short business recommendation that: 
1. Compares the models' mean cross-validation accuracy. 
2. Reports the selected model's test accuracy. 
3. Considers consistency across folds and the risk of incorrect classifications. 
4. Recommends one model and explains why.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

model_lr = LogisticRegression(max_iter=1000)
cv_lr = cross_val_score(model_lr, X_train, y_train, cv=5, scoring='accuracy')

model_knn = KNeighborsClassifier(n_neighbors=5)
cv_knn = cross_val_score(model_knn, X_train, y_train, cv=5, scoring='accuracy')

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
cv_rf = cross_val_score(model_rf, X_train, y_train, cv=5, scoring='accuracy')

print(f"Cv score mean of Logistic model is {cv_lr.mean() * 100:.2f}%")
print(f"Cv score mean of knn model is {cv_knn.mean() * 100:.2f}%")
print(f"Cv score mean of Rainforest model is {cv_rf.mean() * 100:.2f}%")

print(f"\nDifference of Logistic model is {abs(cv_lr.min() - cv_lr.max()) * 100:.2f}%")
print(f"Difference of knn model is {abs(cv_knn.min() - cv_knn.max()) * 100:.2f}%")
print(f"Difference of Rainforest model is {abs(cv_rf.min() - cv_rf.max()) * 100:.2f}%")

# Business should use Logistic model because of this model is more consistent than others.

# ML8

In [ ]:
#1 
"""
Compare Three Models 

Logistic Regression, KNN aur Random Forest train karo. Har model ki test accuracy calculate karke compare karo. 

Concept: accuracy_score(), predict()
"""

from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

model_lr = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))
model_lr.fit(X_train, y_train)
pred_lr = model_lr.predict(X_test)
accu_lr = accuracy_score(y_test, pred_lr)

model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)
pred_knn = model_knn.predict(X_test)
accu_knn = accuracy_score(y_test, pred_knn)

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)
pred_rf = model_rf.predict(X_test)
accu_rf = accuracy_score(y_test, pred_rf)

print(f"Accuracy of Logistic model is {accu_lr * 100:.2f}%")
print(f"Accuracy of knn model is {accu_knn * 100:.2f}%")
print(f"Accuracy of RandomForest model is {accu_rf * 100:.2f}%")

In [ ]:
#2 
"""
Compare Mean Cross-Validation Accuracy 

Teeno models par 5-fold cross-validation run karo aur unki mean accuracy compare karo. 

Concept: cross_val_score(), mean()
"""

from sklearn.model_selection import cross_val_score

cv_lr = cross_val_score(model_lr, X_train, y_train, cv=5, scoring='accuracy')
cv_knn = cross_val_score(model_knn, X_train, y_train, cv=5, scoring='accuracy')
cv_rf = cross_val_score(model_rf, X_train, y_train, cv=5, scoring='accuracy')

print(f"Mean accuracy of Logistic model is {cv_lr.mean() * 100:.2f}%")
print(f"Mean accuracy of knn model is {cv_knn.mean() * 100:.2f}%")
print(f"Mean accuracy of RandomForest model is {cv_rf.mean() * 100:.2f}%")

In [ ]:
#3 
"""
Compare Model Consistency 

Har model ke five fold scores ka highest–lowest difference calculate karo. Identify karo kaunsa model sabse consistent hai. 

Concept: max(), min(), difference
"""

print(f"Difference of Logistic model is {abs(cv_lr.min() - cv_lr.max()) * 100:.2f}%")
print(f"Difference of knn model is {abs(cv_knn.min() - cv_knn.max()) * 100:.2f}%")
print(f"Difference of RandomForest model is {abs(cv_rf.min() - cv_rf.max()) * 100:.2f}%")

In [ ]:
#4 
"""
Create a Model Comparison Table 

Ek Pandas DataFrame banao jisme har model ki test accuracy, mean CV accuracy aur fold difference ho. 

Concept: pd.DataFrame() 
"""

import pandas as pd

comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'Random Forest'],

    'Test Accuracy': [
        accu_lr * 100,
        accu_knn * 100,
        accu_rf * 100
    ],

    'Mean CV Accuracy': [
        cv_lr.mean() * 100,
        cv_knn.mean() * 100,
        cv_rf.mean() * 100
    ],

    'Fold Difference': [
        (cv_lr.max() - cv_lr.min()) * 100,
        (cv_knn.max() - cv_knn.min()) * 100,
        (cv_rf.max() - cv_rf.min()) * 100
    ]
})

print(comparison.round(2))

In [ ]:
#5
"""
Choose the Best Model by Accuracy 

Comparison table se identify karo ki kis model ki mean CV accuracy sabse zyada hai. Us model ka naam aur score print karo. 

Concept: idxmax()
"""

best_model = comparison.loc[comparison['Mean CV Accuracy'].idxmax()]

print(f"Best model: {best_model['Model']}")
print(f"Mean CV Accuracy: {best_model['Mean CV Accuracy']:.2f}%")

In [ ]:
#6 
"""
Compare Precision, Recall and F1-Score 

Teeno models ke macro precision, macro recall aur macro F1-score ko cross-validation se calculate karke compare karo. 

Concept: cross_validate()
"""

from sklearn.model_selection import cross_validate

cv_lr = cross_validate(model_lr,X_train,y_train,cv=5,scoring=['precision_macro', 'recall_macro', 'f1_macro'])
cv_knn = cross_validate(model_knn,X_train,y_train,cv=5,scoring=['precision_macro', 'recall_macro', 'f1_macro'])
cv_rf = cross_validate(model_rf,X_train,y_train,cv=5,scoring=['precision_macro', 'recall_macro', 'f1_macro'])

print(cv_lr)
print(cv_knn)
print(cv_rf)

In [ ]:
#7 
"""
Business Requirement: Consistency 

Ek retailer chahta hai ki model ki performance stable rahe. Aisa model identify karo jiski mean CV accuracy achhi ho aur fold difference relatively low ho.

Concept: Accuracy vs consistency
"""

from sklearn.metrics import accuracy_score

print(comparison.round(2))

# Here you can see that Logistic Model has Best mean cv accuracy with lowest fold difference so Business can use Logistic model

In [ ]:
#8 
"""
Business Requirement: Avoid Wrong Predictions

Maan lo retailer ke liye kisi particular price_range category ko miss karna costly hai. 
Models ke per-class recall ko compare karo aur identify karo ki kaunsa model us category ko sabse achha identify karta hai. 

Concept: recall_score(), classification_report()
"""

from sklearn.metrics import recall_score, classification_report

pred_lr = model_lr.predict(X_test)
pred_knn = model_knn.predict(X_test)
pred_rf = model_rf.predict(X_test)

print("Recall_Lr:", recall_score(y_test, pred_lr, average='macro'))
print("Recall_Knn:", recall_score(y_test, pred_knn, average='macro'))
print("Recall_Rf:", recall_score(y_test, pred_rf, average='macro'))

print(classification_report(y_test, pred_lr))
print(classification_report(y_test, pred_knn))
print(classification_report(y_test, pred_rf))

In [ ]:
#9 
"""
Select a Model Using Multiple Criteria 

Aisa model choose karo jo mean CV accuracy, test accuracy aur consistency ke beech achha balance deta ho.
Apne actual results ke basis par decision explain karo. 

Concept: Evidence-based model select on
"""

best_model = comparison.loc[comparison['Mean CV Accuracy'].idxmax()]

print("Selected Model:", best_model['Model'])
print("Test Accuracy:", best_model['Test Accuracy'])
print("Mean CV Accuracy:", best_model['Mean CV Accuracy'].round(2))
print("Fold Difference:", best_model['Fold Difference'].round(2))

In [ ]:
#10
"""
Final Business Recommendation 

Retailer ke liye ek short recommendation likho: selected model ka naam, uski accuracy, CV consistency, important metric aur use choose karne ka reason. 

Concept: Model select on + business interpretation
"""

import pandas as pd

best = pd.DataFrame({
    'Model' : [best_model['Model']],
    'Accuracy' : [best_model['Test Accuracy']],
    'Consistency' : [best_model['Mean CV Accuracy']],
    'Fold Difference' : [best_model['Fold Difference']]
})

print(best)

print(
    "\nRecommendation: Logistic Regression is the preferred model "
    "\nbecause it has the highest test accuracy (81.75%), "
    "\nthe highest mean CV accuracy (82.38%), and the lowest "
    "\nfold difference (3.44 percentage points). "
    "\nIt offers the best balance of predictive performance "
    "\nand consistency among the three models tested."
)

# ML9

In [ ]:
#1 
"""
Scaling Leakage 

Train-test split se pehle scaling aur split ke baad scaling wale workflows compare karo. 

Concept: StandardScaler, train_test_split
"""

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

X_train_A, X_test_A, y_train_A, y_test_A = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

model_A = LogisticRegression(max_iter=1000)
model_A.fit(X_train_A, y_train_A)

pred_A = model_A.predict(X_test_A)

print("Approach A Accuracy:", accuracy_score(y_test_A, pred_A) * 100)

In [ ]:
X_train_B, X_test_B, y_train_B, y_test_B = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model_B = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000)
)

model_B.fit(X_train_B, y_train_B)

pred_B = model_B.predict(X_test_B)

print("Approach B Accuracy:", accuracy_score(y_test_B, pred_B) * 100)

In [ ]:
#2 
"""
Missing-Value Imputation Leakage 

Median imputation ko sirf training data par fit karke test data par apply karo. 

Concept: SimpleImputer
"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

print(X_train)
print(X_test)

In [ ]:
#3 
"""
Pipeline-Based Preprocessing 

Scaler aur Logistic Regression ko ek pipeline mein combine karo. 

Concept: Pipeline, make_pipeline
"""

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

model_lr = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

model_lr.fit(X_train, y_train)

pred_lr = model_lr.predict(X_test)

print(pred_lr)

In [ ]:
#4
"""
Cross-Validation Leakage 

Pipeline use karke 5-fold cross-validation accuracy calculate karo. 

Concept: cross_val_score 
"""

from sklearn.model_selection import cross_val_score
import numpy as np

cv_lr = cross_val_score(model_lr, X_train, y_train, cv=5, scoring='accuracy')

mean = np.mean(cv_lr)

print("Fold accuracies:", cv_lr)
print(f"Mean CV Accuracy: {mean * 100:.2f}%")

In [ ]:
#5
"""
Target Leakage Detection 

Check karo ki target price_range ya usse derived information accidentally features mein toh nahi hai. 

Concept: Feature validation
"""

print("Target in X:", 'price_range' in x.columns)

print("Feature columns:", x.columns.tolist())

print("Target name:", y.name)

print("X shape:", x.shape)
print("y shape:", y.shape)

In [ ]:
#6
"""
Duplicate-Record Leakage 

Duplicate rows identify karo aur samjho ki similar records train aur test dono mein aane se evaluation kaise misleading ho sakta hai. 

Concept: duplicated(), data splitting
"""

import numpy as np

unique_train = np.unique(X_train, axis=0)
train_duplicates = len(X_train) - len(unique_train)

print("Train duplicate rows:", train_duplicates)


unique_test = np.unique(X_test, axis=0)
test_duplicates = len(X_test) - len(unique_test)

print("Test duplicate rows:", test_duplicates)


train_rows = set(map(tuple, X_train))
test_rows = set(map(tuple, X_test))

common_records = train_rows.intersection(test_rows)

print("Common train-test records:", len(common_records))

In [38]:
#7
"""
Incorrect vs Correct Evaluation 

Leaky preprocessing aur correct pipeline ke evaluation results compare karo. 

Concept: Reliable model evaluation
"""

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score

# A: Incorrect approach — scaling before splitting
scaler_A = StandardScaler()
X_scaled = scaler_A.fit_transform(x)

X_train_A, X_test_A, y_train_A, y_test_A = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model_A = LogisticRegression(max_iter=1000)
model_A.fit(X_train_A, y_train_A)

pred_A = model_A.predict(X_test_A)
accuracy_A = accuracy_score(y_test_A, pred_A)


# B: Correct approach — split first, then use a pipeline
model_B = make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))

model_B.fit(X_train, y_train)
pred_B = model_B.predict(X_test)

accuracy_B = accuracy_score(y_test, pred_B)


# Compare results
print(f"Incorrect approach accuracy: {accuracy_A * 100:.2f}%")
print(f"Correct approach accuracy:   {accuracy_B * 100:.2f}%")
print(f"Difference: {abs(accuracy_A - accuracy_B) * 100:.2f} percentage points")

Incorrect approach accuracy: 81.75%
Correct approach accuracy:   81.75%
Difference: 0.00 percentage points

In [ ]:
#8 
"""
Train-Test Contamination Audit 

Apne existing ML workflow ko audit karo aur leakage ke possible sources identify karo. 

Concept: Data integrity 
"""

import numpy as np
import pandas as pd

# 1. Check train-test sizes
print("Train rows:", X_train.shape[0])
print("Test rows:", X_test.shape[0])

# 2. Check whether target is accidentally inside X
print("Target in X:", 'price_range' in x.columns)

# 3. Check missing values
print("Missing values in train:", pd.isna(X_train).sum().sum())
print("Missing values in test:", pd.isna(X_test).sum().sum())

# 4. Check duplicate rows within train and test
print("Train duplicate rows:",
      len(X_train) - len(np.unique(X_train, axis=0)))

print("Test duplicate rows:",
      len(X_test) - len(np.unique(X_test, axis=0)))

# 5. Check common feature records across train and test
train_rows = set(map(tuple, X_train))
test_rows = set(map(tuple, X_test))

print("Common train-test records:",
      len(train_rows.intersection(test_rows)))

# 6. Train model using a pipeline
model_lr = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000)
)

model_lr.fit(X_train, y_train)
pred_lr = model_lr.predict(X_test)

print("Model predictions:", pred_lr)

In [34]:
#9
"""
Time-Based Leakage 

Retail sales scenario mein decide karo ki prediction ke me kaunsi information available hai aur kaunsi future information leak kar hai. 

Concept: Time-aware validation 
"""

import pandas as pd

# Retail sales example
data = pd.DataFrame({
    "date": ["2026-10-20", "2026-10-21", "2026-10-22"],
    "today_sales": [100, 120, 90],
    "discount": [10, 15, 5],
    "tomorrow_sales": [120, 90, 110],
    "tomorrow_actual_customers": [50, 40, 45]
})

# Information available at prediction time
available_features = [
    "today_sales",
    "discount"
]

# Information not available at prediction time
future_information = [
    "tomorrow_sales",
    "tomorrow_actual_customers"
]

print("Available features:", available_features)
print("Future information:", future_information)

Available features: ['today_sales', 'discount']
Future information: ['tomorrow_sales', 'tomorrow_actual_customers']

In [43]:
#10
"""
Leakage-Free Business Recommendation

Ek complete, leakage-free model evaluation workflow recommend karo aur business decision justify karo. 

Concept: Model reliability and business interpretation
"""

from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import cross_val_score
import numpy as np

# 1. Build the complete pipeline
model_lr = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(),LogisticRegression(max_iter=1000))

# 2. Cross-validation on training data only
cv_scores = cross_val_score(model_lr, X_train, y_train,    cv=5, scoring="accuracy")

print(f"Mean CV Accuracy: {cv_scores.mean() * 100:.2f}%")
print(f"Fold variation: {(cv_scores.max() - cv_scores.min()) * 100:.2f} percentage points")

# 3. Train on the complete training data
model_lr.fit(X_train, y_train)

# 4. Evaluate on untouched test data
pred_lr = model_lr.predict(X_test)

accu_lr = accuracy_score(y_test, pred_lr)
print(f"Test Accuracy: {accu_lr * 100:.2f}%")

# 5. Evaluate each class
print(classification_report(y_test, pred_lr))

Mean CV Accuracy: 82.38%
Fold variation: 3.44 percentage points
Test Accuracy: 81.75%
              precision    recall  f1-score   support

           0       0.92      0.93      0.93       105
           1       0.80      0.77      0.79        91
           2       0.66      0.77      0.71        92
           3       0.89      0.79      0.83       112

    accuracy                           0.82       400
   macro avg       0.82      0.82      0.81       400
weighted avg       0.83      0.82      0.82       400